### ISSUE TITLE
Create a button called "filter" in menubar.

### ISSUE THREAD

**Issue by philipmjohnson** [ics-portfolios/ics-portfolios.github.io#1]
- Provide a button in the menubar to toggle the "filter" widget
- Start by displaying all of the cards for that area.
- Figure out a way to hide certain cards when their interests (etc) aren't selected. (Some kind of Javascript that modifies the DOM and works in conjunction with Semantic UI. You might want to actually ask on the Semantic UI discussion group (or stack overflow).

**Comment by mckuok** [comment]
TODO:

- Delete Browse button on front page
- Add  "All" tab
- Change Browse to Filter, turn it into a button, move to the right top corner
- Filter button should add a new search area on top of the page, instead of redirect to different page
- User Semantic UI Multiple Select to allow users to see what's available on this list.

**Comment by philipmjohnson** [comment]
What do you think about getting rid of the "filter" button in the menubar entirely and have the filter widget in each page at the top by default? If you can make it a fairly small one liner across the top, I think it wouldn't detract and that would be one less button to push. LMK

**Comment by mckuok** [comment]
I think that works, having the multiple select filter widget on the top at all time makes it clear to the users.
